binde = $mainMod SHIFT, S, exec, hyprshot -zm region --clipboard-only

bind = $mainMod, F1, exec, zen

# Scroll with keyboard
bind = , Page_Up, exec, wtype -P Button4
bind = , Page_Down, exec, wtype -P Button5
